python3 run_webcam.py \
--cam_device_id 1 \
--gpu 0 \
--median_filter 0 \
--padding 0 \
--width 640 \
--disp_width 720 \
--disp_source \
--horizontal \
--output_left \
--cycle 0 \
--delay_next_model 1 \
--trim_frame 200 \
--screen_h 2160 \
--screen_w 3840 \
--border_h 0 \
--border_w 10 
